"""add_social_links_to_users

Revision ID: 11e6fbef7cb0
Revises: c2f3a8b94567
Create Date: 2025-12-02 20:39:07.085046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11e6fbef7cb0'
down_revision: Union[str, None] = 'c2f3a8b94567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'social_links')
    # ### end Alembic commands ###
