"""add github_username to users

Revision ID: 5dab0354d470
Revises: 003
Create Date: 2025-12-02 01:14:19.919237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dab0354d470'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('github_repositories_github_repo_id_key', 'github_repositories', type_='unique')
    op.drop_index('ix_github_repositories_github_repo_id', table_name='github_repositories')
    op.create_index(op.f('ix_github_repositories_github_repo_id'), 'github_repositories', ['github_repo_id'], unique=True)
    op.drop_constraint('profiles_custom_domain_key', 'profiles', type_='unique')
    op.drop_constraint('profiles_slug_key', 'profiles', type_='unique')
    op.drop_index('ix_profiles_custom_domain', table_name='profiles')
    op.create_index(op.f('ix_profiles_custom_domain'), 'profiles', ['custom_domain'], unique=True)
    op.drop_index('ix_profiles_slug', table_name='profiles')
    op.create_index(op.f('ix_profiles_slug'), 'profiles', ['slug'], unique=True)
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.alter_column('users', 'is_github_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_github_id_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_github_id', table_name='users')
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.create_index('ix_users_github_id', 'users', ['github_id'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_github_id_key', 'users', ['github_id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'is_github_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'github_username')
    op.drop_index(op.f('ix_profiles_slug'), table_name='profiles')
    op.create_index('ix_profiles_slug', 'profiles', ['slug'], unique=False)
    op.drop_index(op.f('ix_profiles_custom_domain'), table_name='profiles')
    op.create_index('ix_profiles_custom_domain', 'profiles', ['custom_domain'], unique=False)
    op.create_unique_constraint('profiles_slug_key', 'profiles', ['slug'])
    op.create_unique_constraint('profiles_custom_domain_key', 'profiles', ['custom_domain'])
    op.drop_index(op.f('ix_github_repositories_github_repo_id'), table_name='github_repositories')
    op.create_index('ix_github_repositories_github_repo_id', 'github_repositories', ['github_repo_id'], unique=False)
    op.create_unique_constraint('github_repositories_github_repo_id_key', 'github_repositories', ['github_repo_id'])
    # ### end Alembic commands ###
