"""add post_views table

Revision ID: 925b074574a8
Revises: 60b0679e4368
Create Date: 2025-12-02 21:44:38.754508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925b074574a8'
down_revision: Union[str, None] = '60b0679e4368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('view_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_views_post_date', 'post_views', ['post_id', 'view_date'], unique=True)
    op.create_index('ix_post_views_post_id', 'post_views', ['post_id'], unique=False)
    op.create_index('ix_post_views_view_date', 'post_views', ['view_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_views_view_date', table_name='post_views')
    op.drop_index('ix_post_views_post_id', table_name='post_views')
    op.drop_index('ix_post_views_post_date', table_name='post_views')
    op.drop_table('post_views')
    # ### end Alembic commands ###
