"""add_blog_folders_and_update_blog_posts

Revision ID: b1cca9590232
Revises: 5dab0354d470
Create Date: 2025-12-02 18:50:04.604077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1cca9590232'
down_revision: Union[str, None] = '5dab0354d470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_expanded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_blog_folders_parent_id', 'blog_folders', ['parent_id'], unique=False)
    op.create_index('ix_blog_folders_user_id', 'blog_folders', ['user_id'], unique=False)
    op.add_column('blog_posts', sa.Column('folder_id', sa.String(length=36), nullable=True))
    op.add_column('blog_posts', sa.Column('content_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('blog_posts', sa.Column('github_repo_id', sa.String(length=36), nullable=True))
    op.create_index('ix_blog_posts_folder_id', 'blog_posts', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'blog_posts', 'blog_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'blog_posts', 'github_repositories', ['github_repo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_index('ix_blog_posts_folder_id', table_name='blog_posts')
    op.drop_column('blog_posts', 'github_repo_id')
    op.drop_column('blog_posts', 'content_blocks')
    op.drop_column('blog_posts', 'folder_id')
    op.drop_index('ix_blog_folders_user_id', table_name='blog_folders')
    op.drop_index('ix_blog_folders_parent_id', table_name='blog_folders')
    op.drop_table('blog_folders')
    # ### end Alembic commands ###
